set_property IOSTANDARD LVCMOS25 [get_ports TRX_CLK_OUT]
set_property IOSTANDARD LVCMOS25 [get_ports {TRX_CTRL_IN[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TRX_CTRL_IN[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TRX_CTRL_IN[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TRX_CTRL_IN[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TRX_CTRL_OUT[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TRX_CTRL_OUT[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TRX_CTRL_OUT[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TRX_CTRL_OUT[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TRX_CTRL_OUT[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TRX_CTRL_OUT[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TRX_CTRL_OUT[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TRX_CTRL_OUT[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports TRX_DATA_CLK]
set_property IOSTANDARD LVCMOS25 [get_ports TRX_EN]
set_property IOSTANDARD LVCMOS25 [get_ports {TRX_EN_AGC[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports TRX_FBCLK]
set_property IOSTANDARD LVCMOS25 [get_ports {TRX_P0_TXDATA[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TRX_P0_TXDATA[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TRX_P0_TXDATA[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TRX_P0_TXDATA[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TRX_P0_TXDATA[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TRX_P0_TXDATA[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TRX_P0_TXDATA[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TRX_P0_TXDATA[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TRX_P0_TXDATA[8]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TRX_P0_TXDATA[9]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TRX_P0_TXDATA[10]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TRX_P0_TXDATA[11]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TRX_P1_RXDATA[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TRX_P1_RXDATA[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TRX_P1_RXDATA[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TRX_P1_RXDATA[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TRX_P1_RXDATA[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TRX_P1_RXDATA[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TRX_P1_RXDATA[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TRX_P1_RXDATA[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TRX_P1_RXDATA[8]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TRX_P1_RXDATA[9]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TRX_P1_RXDATA[10]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TRX_P1_RXDATA[11]}]
set_property IOSTANDARD LVCMOS25 [get_ports {TRX_RESETn[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports TRX_RXFRAME]
set_property IOSTANDARD LVCMOS25 [get_ports TRX_SPI_io0_io]
set_property IOSTANDARD LVCMOS25 [get_ports TRX_SPI_io1_io]
set_property IOSTANDARD LVCMOS25 [get_ports TRX_SPI_sck_io]
set_property IOSTANDARD LVCMOS25 [get_ports {TRX_SPI_ss_io[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports TRX_TXFRAME]
set_property IOSTANDARD LVCMOS25 [get_ports TRX_TXNRX]
set_property IOSTANDARD LVCMOS25 [get_ports {TRX_SYNC_IN[0]}]
set_property PULLDOWN true [get_ports TRX_CLK_OUT]
set_property PULLDOWN true [get_ports {TRX_CTRL_IN[0]}]
set_property PULLDOWN true [get_ports {TRX_CTRL_IN[1]}]
set_property PULLDOWN true [get_ports {TRX_CTRL_IN[2]}]
set_property PULLDOWN true [get_ports {TRX_CTRL_IN[3]}]
set_property PULLDOWN true [get_ports {TRX_CTRL_OUT[0]}]
set_property PULLDOWN true [get_ports {TRX_CTRL_OUT[1]}]
set_property PULLDOWN true [get_ports {TRX_CTRL_OUT[2]}]
set_property PULLDOWN true [get_ports {TRX_CTRL_OUT[3]}]
set_property PULLDOWN true [get_ports {TRX_CTRL_OUT[4]}]
set_property PULLDOWN true [get_ports {TRX_CTRL_OUT[5]}]
set_property PULLDOWN true [get_ports {TRX_CTRL_OUT[6]}]
set_property PULLDOWN true [get_ports {TRX_CTRL_OUT[7]}]
set_property PULLDOWN true [get_ports TRX_DATA_CLK]
set_property PULLDOWN true [get_ports TRX_EN]
set_property PULLDOWN true [get_ports {TRX_EN_AGC[0]}]
set_property PULLDOWN true [get_ports TRX_FBCLK]
set_property PULLDOWN true [get_ports {TRX_P0_TXDATA[0]}]
set_property PULLDOWN true [get_ports {TRX_P0_TXDATA[1]}]
set_property PULLDOWN true [get_ports {TRX_P0_TXDATA[2]}]
set_property PULLDOWN true [get_ports {TRX_P0_TXDATA[3]}]
set_property PULLDOWN true [get_ports {TRX_P0_TXDATA[4]}]
set_property PULLDOWN true [get_ports {TRX_P0_TXDATA[5]}]
set_property PULLDOWN true [get_ports {TRX_P0_TXDATA[6]}]
set_property PULLDOWN true [get_ports {TRX_P0_TXDATA[7]}]
set_property PULLDOWN true [get_ports {TRX_P0_TXDATA[8]}]
set_property PULLDOWN true [get_ports {TRX_P0_TXDATA[9]}]
set_property PULLDOWN true [get_ports {TRX_P0_TXDATA[10]}]
set_property PULLDOWN true [get_ports {TRX_P0_TXDATA[11]}]
set_property PULLDOWN true [get_ports {TRX_P1_RXDATA[0]}]
set_property PULLDOWN true [get_ports {TRX_P1_RXDATA[1]}]
set_property PULLDOWN true [get_ports {TRX_P1_RXDATA[2]}]
set_property PULLDOWN true [get_ports {TRX_P1_RXDATA[3]}]
set_property PULLDOWN true [get_ports {TRX_P1_RXDATA[4]}]
set_property PULLDOWN true [get_ports {TRX_P1_RXDATA[5]}]
set_property PULLDOWN true [get_ports {TRX_P1_RXDATA[6]}]
set_property PULLDOWN true [get_ports {TRX_P1_RXDATA[7]}]
set_property PULLDOWN true [get_ports {TRX_P1_RXDATA[8]}]
set_property PULLDOWN true [get_ports {TRX_P1_RXDATA[9]}]
set_property PULLDOWN true [get_ports {TRX_P1_RXDATA[10]}]
set_property PULLDOWN true [get_ports {TRX_P1_RXDATA[11]}]
set_property PULLDOWN true [get_ports {TRX_RESETn[0]}]
set_property PULLDOWN true [get_ports TRX_RXFRAME]
set_property PULLDOWN true [get_ports TRX_SPI_io0_io]
set_property PULLDOWN true [get_ports TRX_SPI_io1_io]
set_property PULLDOWN true [get_ports TRX_SPI_sck_io]
set_property PULLUP true [get_ports {TRX_SPI_ss_io[0]}]
set_property PULLDOWN true [get_ports TRX_TXFRAME]
set_property PULLDOWN true [get_ports TRX_TXNRX]
set_property PULLDOWN true [get_ports {TRX_SYNC_IN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports RESETn]
set_property IOSTANDARD LVCMOS33 [get_ports PCIe_RESETn]
set_property IOSTANDARD LVCMOS33 [get_ports {PCIe_CLKREQn[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports FLASH_QSPI_io0_io]
set_property IOSTANDARD LVCMOS33 [get_ports FLASH_QSPI_io1_io]
set_property IOSTANDARD LVCMOS33 [get_ports FLASH_QSPI_io2_io]
set_property IOSTANDARD LVCMOS33 [get_ports FLASH_QSPI_io3_io]
set_property IOSTANDARD LVCMOS33 [get_ports {FLASH_QSPI_ss_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO0_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO0_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO1_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO1_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports I2S_BCLK_IN]
set_property DRIVE 12 [get_ports FLASH_QSPI_io0_io]
set_property DRIVE 12 [get_ports FLASH_QSPI_io1_io]
set_property DRIVE 12 [get_ports FLASH_QSPI_io2_io]
set_property DRIVE 12 [get_ports FLASH_QSPI_io3_io]
set_property DRIVE 12 [get_ports {FLASH_QSPI_ss_io[0]}]
set_property DRIVE 12 [get_ports {GPIO0_tri_io[0]}]
set_property DRIVE 12 [get_ports {GPIO0_tri_io[1]}]
set_property DRIVE 12 [get_ports {GPIO1_tri_io[0]}]
set_property DRIVE 12 [get_ports {GPIO1_tri_io[1]}]
set_property SLEW SLOW [get_ports FLASH_QSPI_io0_io]
set_property SLEW SLOW [get_ports FLASH_QSPI_io1_io]
set_property SLEW SLOW [get_ports FLASH_QSPI_io2_io]
set_property SLEW SLOW [get_ports FLASH_QSPI_io3_io]
set_property SLEW SLOW [get_ports {FLASH_QSPI_ss_io[0]}]
set_property SLEW SLOW [get_ports {GPIO0_tri_io[0]}]
set_property SLEW SLOW [get_ports {GPIO0_tri_io[1]}]
set_property SLEW SLOW [get_ports {GPIO1_tri_io[0]}]
set_property SLEW SLOW [get_ports {GPIO1_tri_io[1]}]
set_property PACKAGE_PIN M9 [get_ports ADCIN_MAIN_v_n]

set_property PACKAGE_PIN T19 [get_ports {FLASH_QSPI_ss_io[0]}]
set_property PACKAGE_PIN P22 [get_ports FLASH_QSPI_io0_io]
set_property PACKAGE_PIN R22 [get_ports FLASH_QSPI_io1_io]
set_property PACKAGE_PIN R21 [get_ports FLASH_QSPI_io3_io]
set_property PACKAGE_PIN P21 [get_ports FLASH_QSPI_io2_io]

set_property PACKAGE_PIN M15 [get_ports {TRX_CTRL_IN[0]}]
set_property PACKAGE_PIN N18 [get_ports {TRX_CTRL_IN[1]}]
set_property PACKAGE_PIN N20 [get_ports {TRX_CTRL_IN[2]}]
set_property PACKAGE_PIN N19 [get_ports {TRX_CTRL_IN[3]}]
set_property PACKAGE_PIN M16 [get_ports {TRX_P0_TXDATA[9]}]
set_property PACKAGE_PIN M17 [get_ports {TRX_P0_TXDATA[7]}]
set_property PACKAGE_PIN M18 [get_ports {TRX_P0_TXDATA[5]}]
set_property PACKAGE_PIN M13 [get_ports {TRX_P0_TXDATA[3]}]
set_property PACKAGE_PIN L13 [get_ports {TRX_P0_TXDATA[1]}]
set_property PACKAGE_PIN L14 [get_ports {TRX_P0_TXDATA[4]}]
set_property PACKAGE_PIN L15 [get_ports {TRX_P0_TXDATA[2]}]
set_property PACKAGE_PIN L16 [get_ports {TRX_P0_TXDATA[0]}]
set_property PACKAGE_PIN L18 [get_ports {TRX_P0_TXDATA[6]}]
set_property PACKAGE_PIN L19 [get_ports {TRX_P0_TXDATA[8]}]
set_property PACKAGE_PIN L20 [get_ports {TRX_P0_TXDATA[11]}]
set_property PACKAGE_PIN L21 [get_ports {TRX_P0_TXDATA[10]}]
set_property PACKAGE_PIN K18 [get_ports TRX_FBCLK]
set_property PACKAGE_PIN J19 [get_ports TRX_DATA_CLK]
set_property PACKAGE_PIN K21 [get_ports TRX_TXFRAME]
set_property PACKAGE_PIN K22 [get_ports TRX_RXFRAME]
set_property PACKAGE_PIN J20 [get_ports TRX_CLK_OUT]
set_property PACKAGE_PIN J21 [get_ports {TRX_P1_RXDATA[11]}]
set_property PACKAGE_PIN J22 [get_ports {TRX_P1_RXDATA[10]}]
set_property PACKAGE_PIN K17 [get_ports {TRX_P1_RXDATA[9]}]
set_property PACKAGE_PIN K16 [get_ports {TRX_P1_RXDATA[7]}]
set_property PACKAGE_PIN K14 [get_ports {TRX_P1_RXDATA[1]}]
set_property PACKAGE_PIN K13 [get_ports {TRX_P1_RXDATA[3]}]
set_property PACKAGE_PIN H13 [get_ports {TRX_P1_RXDATA[5]}]
set_property PACKAGE_PIN H14 [get_ports {TRX_P1_RXDATA[0]}]
set_property PACKAGE_PIN H15 [get_ports {TRX_P1_RXDATA[2]}]
set_property PACKAGE_PIN H17 [get_ports {TRX_P1_RXDATA[4]}]
set_property PACKAGE_PIN H18 [get_ports {TRX_P1_RXDATA[6]}]
set_property PACKAGE_PIN N22 [get_ports {TRX_CTRL_OUT[0]}]
set_property PACKAGE_PIN G22 [get_ports {TRX_CTRL_OUT[4]}]
set_property PACKAGE_PIN G21 [get_ports {TRX_P1_RXDATA[8]}]
set_property PACKAGE_PIN G13 [get_ports {TRX_SPI_ss_io[0]}]
set_property PACKAGE_PIN G15 [get_ports TRX_SPI_sck_io]
set_property PACKAGE_PIN G18 [get_ports TRX_SPI_io1_io]
set_property PACKAGE_PIN G17 [get_ports TRX_SPI_io0_io]
set_property PACKAGE_PIN G16 [get_ports {TRX_RESETn[0]}]
set_property PACKAGE_PIN F16 [get_ports TRX_EN]
set_property PACKAGE_PIN F15 [get_ports {TRX_EN_AGC[0]}]
set_property PACKAGE_PIN F14 [get_ports TRX_TXNRX]
set_property PACKAGE_PIN E21 [get_ports {TRX_CTRL_OUT[5]}]
set_property PACKAGE_PIN E19 [get_ports {TRX_CTRL_OUT[7]}]
set_property PACKAGE_PIN D17 [get_ports {TRX_CTRL_OUT[3]}]
set_property PACKAGE_PIN D19 [get_ports {TRX_CTRL_OUT[6]}]
set_property PACKAGE_PIN D21 [get_ports {TRX_CTRL_OUT[2]}]
set_property PACKAGE_PIN D22 [get_ports {TRX_CTRL_OUT[1]}]
set_property PACKAGE_PIN F18 [get_ports {TRX_SYNC_IN[0]}]

set_property IOSTANDARD DIFF_SSTL135 [get_ports DDR3_CLK_IN_clk_p]

create_power_rail 1V0 -members { Vccint Vccbram MGTAVcc }
create_power_rail 1V2 -members { Vcco12 MGTAVtt }
create_power_rail 1V35 -members { Vcco135 }
create_power_rail 1V8 -members { Vccaux Vccaux_io Vcco18 Vccadc }
create_power_rail 2V5 -members { Vcco25 }
create_power_rail 3V3 -members { Vcco33 }
create_power_rail 5V0 -members { 3V3 2V5 1V8 1V35 1V2 }
create_power_rail PCIE_12V0 -members { 5V0 1V0 }
create_power_rail USB_VBUS
create_power_rail VEXT
set_operating_conditions -board_layers 4to7
set_operating_conditions -heatsink none
set_operating_conditions -voltage {1V0 1.000} -supply_current_budget {1V0 6.000}
set_operating_conditions -voltage {1V35 1.350} -supply_current_budget {1V35 2.000}
set_operating_conditions -voltage {1V2 1.200} -supply_current_budget {1V2 2.000}
set_operating_conditions -voltage {1V8 1.800} -supply_current_budget {1V8 2.000}
set_operating_conditions -voltage {2V5 2.500} -supply_current_budget {2V5 2.000}
set_operating_conditions -voltage {3V3 3.300} -supply_current_budget {3V3 2.000}
set_operating_conditions -voltage {5V0 5.200} -supply_current_budget {5V0 6.000}
set_operating_conditions -voltage {PCIE_12V0 12.000} -supply_current_budget {PCIE_12V0 5.500}
set_operating_conditions -voltage {USB_VBUS 15.000} -supply_current_budget {USB_VBUS 3.000}
set_operating_conditions -voltage {VEXT 12.000} -supply_current_budget {VEXT 3.000}
