
///////////////////////////////////////////////////////////////////////////
//NOTE: This file has been automatically generated by Vivado.
///////////////////////////////////////////////////////////////////////////

package icyradio_axi_dmac_0_1_pkg;

///////////////////////////////////////////////////////////////////////////
// These parameters are named after the component for use in your verification
// environment.
///////////////////////////////////////////////////////////////////////////
  parameter icyradio_axi_dmac_0_1_ID                      = 0;
  parameter icyradio_axi_dmac_0_1_DMA_DATA_WIDTH_SRC      = 64;
  parameter icyradio_axi_dmac_0_1_DMA_DATA_WIDTH_DEST     = 64;
  parameter icyradio_axi_dmac_0_1_DMA_LENGTH_WIDTH        = 16;
  parameter icyradio_axi_dmac_0_1_DMA_2D_TRANSFER         = 0;
  parameter icyradio_axi_dmac_0_1_ASYNC_CLK_REQ_SRC       = 0;
  parameter icyradio_axi_dmac_0_1_ASYNC_CLK_SRC_DEST      = 1;
  parameter icyradio_axi_dmac_0_1_ASYNC_CLK_DEST_REQ      = 1;
  parameter icyradio_axi_dmac_0_1_AXI_SLICE_DEST          = 0;
  parameter icyradio_axi_dmac_0_1_AXI_SLICE_SRC           = 0;
  parameter icyradio_axi_dmac_0_1_SYNC_TRANSFER_START     = 0;
  parameter icyradio_axi_dmac_0_1_CYCLIC                  = 0;
  parameter icyradio_axi_dmac_0_1_DMA_AXI_PROTOCOL_DEST   = 0;
  parameter icyradio_axi_dmac_0_1_DMA_AXI_PROTOCOL_SRC    = 0;
  parameter icyradio_axi_dmac_0_1_DMA_TYPE_DEST           = 1;
  parameter icyradio_axi_dmac_0_1_DMA_TYPE_SRC            = 0;
  parameter icyradio_axi_dmac_0_1_DMA_AXI_ADDR_WIDTH      = 31;
  parameter icyradio_axi_dmac_0_1_MAX_BYTES_PER_BURST     = 128;
  parameter icyradio_axi_dmac_0_1_FIFO_SIZE               = 8;
  parameter icyradio_axi_dmac_0_1_AXI_ID_WIDTH_SRC        = 1;
  parameter icyradio_axi_dmac_0_1_AXI_ID_WIDTH_DEST       = 1;
  parameter icyradio_axi_dmac_0_1_DISABLE_DEBUG_REGISTERS = 0;
//////////////////////////////////////////////////////////////////////////

endpackage : icyradio_axi_dmac_0_1_pkg
