
///////////////////////////////////////////////////////////////////////////
//NOTE: This file has been automatically generated by Vivado.
///////////////////////////////////////////////////////////////////////////

package icyradio_axi_dmac_rf_tx_0_pkg;

///////////////////////////////////////////////////////////////////////////
// These parameters are named after the component for use in your verification
// environment.
///////////////////////////////////////////////////////////////////////////
  parameter icyradio_axi_dmac_rf_tx_0_ID                      = 3;
  parameter icyradio_axi_dmac_rf_tx_0_DMA_DATA_WIDTH_SRC      = 64;
  parameter icyradio_axi_dmac_rf_tx_0_DMA_DATA_WIDTH_DEST     = 32;
  parameter icyradio_axi_dmac_rf_tx_0_DMA_LENGTH_WIDTH        = 24;
  parameter icyradio_axi_dmac_rf_tx_0_DMA_2D_TRANSFER         = 0;
  parameter icyradio_axi_dmac_rf_tx_0_ASYNC_CLK_REQ_SRC       = 0;
  parameter icyradio_axi_dmac_rf_tx_0_ASYNC_CLK_SRC_DEST      = 0;
  parameter icyradio_axi_dmac_rf_tx_0_ASYNC_CLK_DEST_REQ      = 0;
  parameter icyradio_axi_dmac_rf_tx_0_AXI_SLICE_DEST          = 0;
  parameter icyradio_axi_dmac_rf_tx_0_AXI_SLICE_SRC           = 0;
  parameter icyradio_axi_dmac_rf_tx_0_SYNC_TRANSFER_START     = 0;
  parameter icyradio_axi_dmac_rf_tx_0_CYCLIC                  = 0;
  parameter icyradio_axi_dmac_rf_tx_0_DMA_AXI_PROTOCOL_DEST   = 0;
  parameter icyradio_axi_dmac_rf_tx_0_DMA_AXI_PROTOCOL_SRC    = 0;
  parameter icyradio_axi_dmac_rf_tx_0_DMA_TYPE_DEST           = 1;
  parameter icyradio_axi_dmac_rf_tx_0_DMA_TYPE_SRC            = 0;
  parameter icyradio_axi_dmac_rf_tx_0_DMA_AXI_ADDR_WIDTH      = 31;
  parameter icyradio_axi_dmac_rf_tx_0_MAX_BYTES_PER_BURST     = 128;
  parameter icyradio_axi_dmac_rf_tx_0_FIFO_SIZE               = 8;
  parameter icyradio_axi_dmac_rf_tx_0_AXI_ID_WIDTH_SRC        = 1;
  parameter icyradio_axi_dmac_rf_tx_0_AXI_ID_WIDTH_DEST       = 1;
  parameter icyradio_axi_dmac_rf_tx_0_DISABLE_DEBUG_REGISTERS = 0;
//////////////////////////////////////////////////////////////////////////

endpackage : icyradio_axi_dmac_rf_tx_0_pkg
