#ifndef __RMU_H__
#define __RMU_H__

#include <em_device.h>

#define RMU_RSTCAUSE_POR_MASK           (RMU_RSTCAUSE_PORST)
#define RMU_RSTCAUSE_BOR_AVDD_MASK      (RMU_RSTCAUSE_PORST | RMU_RSTCAUSE_AVDDBOD)
#define RMU_RSTCAUSE_BOR_DVDD_MASK      (RMU_RSTCAUSE_PORST | RMU_RSTCAUSE_DVDDBOD)
#define RMU_RSTCAUSE_BOR_DECOUPLE_MASK  (RMU_RSTCAUSE_PORST | RMU_RSTCAUSE_DECBOD)
#define RMU_RSTCAUSE_PIN_MASK           (RMU_RSTCAUSE_PORST | RMU_RSTCAUSE_EXTRST)
#define RMU_RSTCAUSE_LOCKUP_MASK        (RMU_RSTCAUSE_PORST | RMU_RSTCAUSE_AVDDBOD | RMU_RSTCAUSE_DVDDBOD | RMU_RSTCAUSE_DECBOD | RMU_RSTCAUSE_LOCKUPRST)
#define RMU_RSTCAUSE_SYSREQ_MASK        (RMU_RSTCAUSE_PORST | RMU_RSTCAUSE_AVDDBOD | RMU_RSTCAUSE_DVDDBOD | RMU_RSTCAUSE_DECBOD | RMU_RSTCAUSE_SYSREQRST)
#define RMU_RSTCAUSE_WDOG_MASK          (RMU_RSTCAUSE_PORST | RMU_RSTCAUSE_AVDDBOD | RMU_RSTCAUSE_DVDDBOD | RMU_RSTCAUSE_DECBOD | RMU_RSTCAUSE_WDOGRST)
#define RMU_RSTCAUSE_BUM_MASK           (RMU_RSTCAUSE_PORST | RMU_RSTCAUSE_DVDDBOD | RMU_RSTCAUSE_DECBOD | RMU_RSTCAUSE_BUMODERST | RMU_RSTCAUSE_EM4RST)
#define RMU_RSTCAUSE_EM4_MASK           (RMU_RSTCAUSE_PORST | RMU_RSTCAUSE_AVDDBOD | RMU_RSTCAUSE_DVDDBOD | RMU_RSTCAUSE_DECBOD | RMU_RSTCAUSE_EM4RST)

#define RMU_RSTCAUSE_POR_COMP           (RMU_RSTCAUSE_PORST)
#define RMU_RSTCAUSE_BOR_AVDD_COMP      (RMU_RSTCAUSE_AVDDBOD)
#define RMU_RSTCAUSE_BOR_DVDD_COMP      (RMU_RSTCAUSE_DVDDBOD)
#define RMU_RSTCAUSE_BOR_DECOUPLE_COMP  (RMU_RSTCAUSE_DECBOD)
#define RMU_RSTCAUSE_PIN_COMP           (RMU_RSTCAUSE_EXTRST)
#define RMU_RSTCAUSE_LOCKUP_COMP        (RMU_RSTCAUSE_LOCKUPRST)
#define RMU_RSTCAUSE_SYSREQ_COMP        (RMU_RSTCAUSE_SYSREQRST)
#define RMU_RSTCAUSE_WDOG_COMP          (RMU_RSTCAUSE_WDOGRST)
#define RMU_RSTCAUSE_BUM_COMP           (RMU_RSTCAUSE_BUMODERST | RMU_RSTCAUSE_EM4RST)
#define RMU_RSTCAUSE_EM4_COMP           (RMU_RSTCAUSE_EM4RST)

#define RMU_RESET_CAUSE_NONE            0
#define RMU_RESET_CAUSE_POR             1
#define RMU_RESET_CAUSE_AVDD_BOD        2
#define RMU_RESET_CAUSE_DVDD_BOD        3
#define RMU_RESET_CAUSE_DECOUPLE_BOD    4
#define RMU_RESET_CAUSE_EXT_PIN         5
#define RMU_RESET_CAUSE_CORE_LOCKUP     6
#define RMU_RESET_CAUSE_SYSRESETREQ     7
#define RMU_RESET_CAUSE_WATCHDOG        8
#define RMU_RESET_CAUSE_BACKUP_MODE     9
#define RMU_RESET_CAUSE_EM4_MODE        10
#define RMU_RESET_CAUSE_UNKNOWN         255

void rmu_init(uint32_t ulPinMode, uint32_t ulSysMode, uint32_t ulLockupMode, uint32_t ulWatchdogMode);

uint8_t rmu_get_reset_reason();
void rmu_clear_reset_reason();

uint8_t rmu_get_reset_state();
void rmu_set_reset_state(uint8_t ubState);

#endif // __RMU_H__
