
///////////////////////////////////////////////////////////////////////////
//NOTE: This file has been automatically generated by Vivado.
///////////////////////////////////////////////////////////////////////////

package icyradio_axi_dmac_rf_tx_2_pkg;

///////////////////////////////////////////////////////////////////////////
// These parameters are named after the component for use in your verification
// environment.
///////////////////////////////////////////////////////////////////////////
  parameter icyradio_axi_dmac_rf_tx_2_ID                      = 0;
  parameter icyradio_axi_dmac_rf_tx_2_DMA_DATA_WIDTH_SRC      = 64;
  parameter icyradio_axi_dmac_rf_tx_2_DMA_DATA_WIDTH_DEST     = 64;
  parameter icyradio_axi_dmac_rf_tx_2_DMA_LENGTH_WIDTH        = 16;
  parameter icyradio_axi_dmac_rf_tx_2_DMA_2D_TRANSFER         = 0;
  parameter icyradio_axi_dmac_rf_tx_2_ASYNC_CLK_REQ_SRC       = 0;
  parameter icyradio_axi_dmac_rf_tx_2_ASYNC_CLK_SRC_DEST      = 1;
  parameter icyradio_axi_dmac_rf_tx_2_ASYNC_CLK_DEST_REQ      = 1;
  parameter icyradio_axi_dmac_rf_tx_2_AXI_SLICE_DEST          = 0;
  parameter icyradio_axi_dmac_rf_tx_2_AXI_SLICE_SRC           = 0;
  parameter icyradio_axi_dmac_rf_tx_2_SYNC_TRANSFER_START     = 0;
  parameter icyradio_axi_dmac_rf_tx_2_CYCLIC                  = 0;
  parameter icyradio_axi_dmac_rf_tx_2_DMA_AXI_PROTOCOL_DEST   = 0;
  parameter icyradio_axi_dmac_rf_tx_2_DMA_AXI_PROTOCOL_SRC    = 0;
  parameter icyradio_axi_dmac_rf_tx_2_DMA_TYPE_DEST           = 1;
  parameter icyradio_axi_dmac_rf_tx_2_DMA_TYPE_SRC            = 0;
  parameter icyradio_axi_dmac_rf_tx_2_DMA_AXI_ADDR_WIDTH      = 32;
  parameter icyradio_axi_dmac_rf_tx_2_MAX_BYTES_PER_BURST     = 128;
  parameter icyradio_axi_dmac_rf_tx_2_FIFO_SIZE               = 8;
  parameter icyradio_axi_dmac_rf_tx_2_AXI_ID_WIDTH_SRC        = 1;
  parameter icyradio_axi_dmac_rf_tx_2_AXI_ID_WIDTH_DEST       = 1;
  parameter icyradio_axi_dmac_rf_tx_2_DISABLE_DEBUG_REGISTERS = 0;
//////////////////////////////////////////////////////////////////////////

endpackage : icyradio_axi_dmac_rf_tx_2_pkg
