#include "port.h"

void port_init()
{
    // NC - Not Connected (not available in mcu package)
    // NR - Not routed (no routing to pin on pcb, floating)
    // NU - Not used (not currently in use)

    // Port A
    // PA00 - PMC_LED
    // PA01 - nFPGA_INIT
    // PA02 - VBUS_VSENSE - PIOMUX B - (ADC - AIN 0)
    // PA03 - VIN_VSENSE - PIOMUX B - (ADC - AIN 1)
    // PA04 - 12V0_VSENSE - PIOMUX B - (ADC - AIN 4)
    // PA05 - VEXT_VSENSE - PIOMUX B - (ADC - AIN 5)
    // PA06 - VEXT_EN
    // PA07 - UPD350-B SPI_MOSI_SI - PIOMUX D - (SERCOM 0 - PAD 3)
    // PA08 - UPD350-B SPI_MISO - PIOMUX C - (SERCOM 0 - PAD 0)
    // PA09 - UPD350-B SPI_CLK - PIOMUX C - (SERCOM 0 - PAD 1)
    // PA10 - UPD350-B nSPI_CS - PIOMUX C - (SERCOM 0 - PAD 2)
    // PA11 - UPD350-B SPI_MOSI - PIOMUX C - (SERCOM 0 - PAD 3)
    // PA12 - NC
    // PA13 - NC
    // PA14 - UPD350-B nIRQ
    // PA15 - 12V0_EN
    // PA16 - PM_I2C_SDA - PIOMUX C - (SERCOM 1 - PAD 0)
    // PA17 - PM_I2C_SCL - PIOMUX C - (SERCOM 1 - PAD 1)
    // PA18 - PMC_SWO - PIOMUX D - (SERCOM 3 - PAD 2)
    // PA19 - CM4_RUNNING
    // PA20 - NC
    // PA21 - NC
    // PA22 - nCM4_BTLDR
    // PA23 - CM4_GLOBAL_EN
    // PA24 - NC
    // PA25 - NC
    // PA26 - NC
    // PA27 - VBUS_SNK_EN
    // PA28 - CM4_USB_OTG
    // PA29 - NC
    // PA30 - PMC_SWCLK
    // PA31 - PMC_SWDIO
    PORT_REGS->GROUP[0].PORT_DIR = BIT(28) | BIT(27) | BIT(23) | BIT(22) | BIT(18) | BIT(15) | BIT(11) | BIT(10) | BIT(9) | BIT(6) | BIT(1) | BIT(0);
    PORT_REGS->GROUP[0].PORT_OUT = BIT(22) | BIT(17) | BIT(16) | BIT(14) | BIT(10);
    PORT_REGS->GROUP[0].PORT_PINCFG[0] = PORT_PINCFG_DRVSTR_Msk;
    PORT_REGS->GROUP[0].PORT_PINCFG[1] = 0;
    PORT_PERI_MUX_SELECT(0, 2, 1);
    PORT_REGS->GROUP[0].PORT_PINCFG[2] = 0;
    PORT_PERI_MUX_SELECT(0, 3, 1);
    PORT_REGS->GROUP[0].PORT_PINCFG[3] = 0;
    PORT_PERI_MUX_SELECT(0, 4, 1);
    PORT_REGS->GROUP[0].PORT_PINCFG[4] = 0;
    PORT_PERI_MUX_SELECT(0, 5, 1);
    PORT_REGS->GROUP[0].PORT_PINCFG[5] = 0;
    PORT_REGS->GROUP[0].PORT_PINCFG[6] = PORT_PINCFG_DRVSTR_Msk;
    //PORT_PERI_MUX_SELECT(0, 7, 3);
    PORT_REGS->GROUP[0].PORT_PINCFG[7] = 0;
    PORT_PERI_MUX_SELECT(0, 8, 2);
    PORT_REGS->GROUP[0].PORT_PINCFG[8] = PORT_PINCFG_INEN_Msk | PORT_PINCFG_PMUXEN_Msk;
    PORT_PERI_MUX_SELECT(0, 9, 2);
    PORT_REGS->GROUP[0].PORT_PINCFG[9] = PORT_PINCFG_PMUXEN_Msk;
    PORT_REGS->GROUP[0].PORT_PINCFG[10] = 0;
    PORT_PERI_MUX_SELECT(0, 11, 2);
    PORT_REGS->GROUP[0].PORT_PINCFG[11] = PORT_PINCFG_PMUXEN_Msk;
    PORT_REGS->GROUP[0].PORT_PINCFG[14] = PORT_PINCFG_INEN_Msk;
    PORT_REGS->GROUP[0].PORT_PINCFG[15] = PORT_PINCFG_DRVSTR_Msk;
    PORT_PERI_MUX_SELECT(0, 16, 2);
    PORT_REGS->GROUP[0].PORT_PINCFG[16] = PORT_PINCFG_DRVSTR_Msk | PORT_PINCFG_INEN_Msk | PORT_PINCFG_PMUXEN_Msk;
    PORT_PERI_MUX_SELECT(0, 17, 2);
    PORT_REGS->GROUP[0].PORT_PINCFG[17] = PORT_PINCFG_DRVSTR_Msk | PORT_PINCFG_INEN_Msk | PORT_PINCFG_PMUXEN_Msk;
    PORT_PERI_MUX_SELECT(0, 18, 3);
    PORT_REGS->GROUP[0].PORT_PINCFG[18] = PORT_PINCFG_DRVSTR_Msk | PORT_PINCFG_PMUXEN_Msk;
    PORT_REGS->GROUP[0].PORT_PINCFG[19] = PORT_PINCFG_PULLEN_Msk | PORT_PINCFG_INEN_Msk;
    PORT_REGS->GROUP[0].PORT_PINCFG[22] = 0;
    PORT_REGS->GROUP[0].PORT_PINCFG[23] = 0;
    PORT_REGS->GROUP[0].PORT_PINCFG[27] = PORT_PINCFG_DRVSTR_Msk;
    PORT_REGS->GROUP[0].PORT_PINCFG[28] = 0;
    PORT_PERI_MUX_SELECT(0, 30, 6);
    PORT_REGS->GROUP[0].PORT_PINCFG[30] = PORT_PINCFG_INEN_Msk | PORT_PINCFG_PMUXEN_Msk;
    PORT_PERI_MUX_SELECT(0, 31, 6);
    PORT_REGS->GROUP[0].PORT_PINCFG[31] = PORT_PINCFG_DRVSTR_Msk | PORT_PINCFG_INEN_Msk | PORT_PINCFG_PMUXEN_Msk;
}